version: '3'

services:
  python:
    build:
      context: ./
      args:
        - TZ=Asia/Shanghai
    volumes:
      - ./:/var/www
    ports:
      - "5000:5000"
    restart: on-failure
    tty: true
    networks:
      - python

networks:
  python: